add translations
aternosorg/codex-minecraft pull request #82
Opened 2024-07-04 13:33 UTC by DominikDoemsky

2024-07-04 15:39 UTC, pavog requested changes

2024-07-04 15:39 UTC, pavog commented on lang/pt-PT.json
> +    "arclight-version": "Versão ArClight",
Arclight, not ArClight

2024-07-04 15:39 UTC, pavog commented on lang/th.json
> +    "neoforge-version": "เวอร์ชั่น Neoforge",
Neo**F**orge

2024-07-04 15:39 UTC, pavog commented on lang/th.json
> +    "arclight-version": "รุ่นอาร์คไลท์",
They should not translate Arclight

2024-07-04 15:39 UTC, pavog commented on lang/th.json
> +    "custom-skin-loader-version": "เวอร์ชันนักเทียบท่า Skin แบบกำหนดเอง",
They should not translate CustomSkinLoader

2024-07-04 15:39 UTC, pavog commented on lang/vi.json
> +    "minecraft-version": "Phiên bản Minecraftjava và bedrock",
It should be "Minecraft version", not "Minecraft java and bedrock versions".

2024-07-04 16:39 UTC, pavog requested changes
Some issues are not resolved yet. See fil, fr, gl, ...
Make sure to click "Load more..." right below "10 hidden conversations" ;-)

2024-07-05 09:44 UTC, pavog approved these changes

2024-07-05 10:59 UTC, matthi4s approved these changes

2024-07-05 10:59 UTC, merged